import { AppBar, Toolbar, Typography } from '@material-ui/core'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar position="static">
        <Toolbar>
          <Typography variant="h6">
            Ny-a.github.io
          </Typography>
        </Toolbar>
      </AppBar>

      <div className="container">
        <main className={styles.main}>
          <h2 className={styles.title}>
            S. Furukawa
          </h2>

          <p className={styles.description}>
            学部生: 放送大学<br />
            仕事: ソフトウェアエンジニア
          </p>

          <div className={styles.grid}>
            <a href="https://github.com/ny-a" className={styles.card}>
              <h2>GitHub</h2>
            </a>

            <a href="https://ny-a.github.io/blog2" className={styles.card}>
              <h2>Blog</h2>
            </a>

            <a href="https://wiki.archlinux.jp" className={styles.card}>
              <h2>ArchWiki-jp</h2>
              <p>ArchWiki 日本語版の翻訳をしています。</p>
            </a>

            <a href="https://twitter.com/nyaarch64" className={styles.card}>
              <h2>Contact</h2>
              <p>
                Twitter @nyaarch64
              </p>
            </a>
          </div>
        </main>
      </div>
    </div>
  )
}
